version: '3'

services:
  php_apache:
    container_name: php-apache
    build:
      context: docker/apache
    restart: always
    depends_on:
      - db
      - composer
    ports:
      - 8080:80
    working_dir: /app
    volumes:
      - ./:/app/
      - ./docker/apache/php.ini/:/opt/docker/etc/php/php.ini
    environment:
      WEB_DOCUMENT_ROOT: /app/web
      PHP_DISMOD: mysql-client, unzip, curl, git
#  nginx:
#    container_name: nginx
#    image: nginx
#    ports:
#      - "8080:80"
#    volumes:
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - .:/var/www
#    restart: always
#    working_dir: "/var/www"
#    depends_on:
#      - php
#  php:
#    container_name: php
#    build:
#      context: docker/php
#      args:
#        TIMEZONE: Europe/Brussels
#    volumes:
#      - .:/var/www
#      - /var/run/docker.sock:/var/run/docker.sock
#    restart: always
#    working_dir: "/var/www"
#    depends_on:
#      - db
#      - composer
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
  composer:
    container_name: composer
    image: composer
    volumes:
      - .:/var/www
    working_dir: "/var/www"
