entity_type_groups:
  node:
    homepage:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      dublin_core: dublin_core
      hreflang: hreflang
    vacature:
      basic: basic
